-- BREAKING WASTE - ESTRUCTURA DE BASE DE DATOS
-- Ejecuta todo este archivo en Supabase > SQL Editor > New query > Run.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null default '',
    email text not null default '',
    phone text default '',
    address text default '',
    container_name text default '',
    role text not null default 'user' check (role in ('user', 'admin')),
    dark_mode boolean not null default false,
    notifications boolean not null default true,
    show_percentage boolean not null default true,
    sound boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.sensor_readings (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    container_name text default '',
    percentage integer not null check (percentage between 0 and 100),
    sensor_50 boolean not null default false,
    sensor_90 boolean not null default false,
    connected boolean not null default true,
    measured_at timestamptz not null default now()
);

create index if not exists sensor_readings_user_id_idx
on public.sensor_readings(user_id);

create index if not exists sensor_readings_measured_at_idx
on public.sensor_readings(measured_at desc);

alter table public.profiles enable row level security;
alter table public.sensor_readings enable row level security;

grant select, insert, update on public.profiles to authenticated;
grant select, insert on public.sensor_readings to authenticated;

create policy "Usuarios pueden ver su perfil"
on public.profiles for select
to authenticated
using ((select auth.uid()) = id);

create policy "Usuarios pueden crear su perfil"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

create policy "Usuarios pueden actualizar su perfil"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

create policy "Usuarios pueden ver sus lecturas"
on public.sensor_readings for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Usuarios pueden guardar sus lecturas"
on public.sensor_readings for insert
to authenticated
with check ((select auth.uid()) = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (
        id,
        full_name,
        email,
        phone,
        address,
        container_name
    )
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.email, ''),
        coalesce(new.raw_user_meta_data ->> 'phone', ''),
        coalesce(new.raw_user_meta_data ->> 'address', ''),
        coalesce(new.raw_user_meta_data ->> 'container_name', '')
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
